### ISSUE TITLE
this code converts voc2012 to coco with some problems?

### ISSUE THREAD

**Issue by gtwell** [CivilNet/Gemfield#2]
this code converts voc2012 to coco with some problems?

**Comment by gtwell** [comment]
Annotations_Val\2009_000001.xml
Traceback (most recent call last):
  File "pascal_voc_xml2json.py", line 177, in <module>
    parseXmlFiles(xml_path)
  File "pascal_voc_xml2json.py", line 158, in parseXmlFiles
    raise Exception('xml structure broken at bndbox tag')
Exception: xml structure broken at bndbox tag

**Comment by gtwell** [comment]
no reply
