### ISSUE TITLE
ValuError when converting floating point bndbox coordinates 

### ISSUE THREAD

**Issue by saiabinesh** [CivilNet/Gemfield#4]
**Full error below**

add image with IMG_8184.jpg and {'height': 2448, 'width': 3264, 'depth': 3}
Traceback (most recent call last):
  File "pascal_voc_xml2json.py", line 172, in <module>
    parseXmlFiles(xml_path)
  File "pascal_voc_xml2json.py", line 146, in parseXmlFiles
    bndbox[option.tag] = int(option.text)
ValueError: invalid literal for int() with base 10: '2006.8831168831168'

**Comment by gemfield** [comment]
A float type is expetecd, while here you have a string type value.

**Comment by saiabinesh** [comment]
But it seems like the program converts all coordinates to int .
When I changed it to float, the program worked.
